// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ApproveTaskReq struct {
	Id      string `path:"id"`
	Comment string `json:"comment,optional"`
}

type ApproveTaskResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type CancelTaskReq struct {
	Id     string `path:"id"`
	Reason string `json:"reason,optional"`
}

type CancelTaskResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type CreateTaskReq struct {
	Title            string   `json:"title"`
	RepoPath         string   `json:"repoPath"`
	Prompt           string   `json:"prompt"`
	Mode             string   `json:"mode,options=analyze|patch"`
	ApprovalRequired bool     `json:"approvalRequired,optional"`
	MaxSteps         int64    `json:"maxSteps,default=10"`
	AllowedPaths     []string `json:"allowedPaths,optional"`
	DeniedPaths      []string `json:"deniedPaths,optional"`
}

type CreateTaskResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type ExecutionItem struct {
	Id            string `json:"id"`
	TaskId        string `json:"taskId"`
	Status        string `json:"status"`
	StartedAt     string `json:"startedAt"`
	FinishedAt    string `json:"finishedAt"`
	ResultSummary string `json:"resultSummary"`
}

type GetTaskExecutionsReq struct {
	Id string `path:"id"`
}

type GetTaskLogsReq struct {
	Id string `path:"id"`
}

type GetTaskReq struct {
	Id string `path:"id"`
}

type LogItem struct {
	Step       int64  `json:"step"`
	Level      string `json:"level"`
	Message    string `json:"message"`
	ToolName   string `json:"toolName"`
	OccurredAt string `json:"occurredAt"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"accessToken"`
	ExpiresIn   int64  `json:"expiresIn"`
}

type TaskDetailResp struct {
	Id               string   `json:"id"`
	Title            string   `json:"title"`
	RepoPath         string   `json:"repoPath"`
	Prompt           string   `json:"prompt"`
	Mode             string   `json:"mode"`
	Status           string   `json:"status"`
	ApprovalRequired bool     `json:"approvalRequired"`
	MaxSteps         int64    `json:"maxSteps"`
	AllowedPaths     []string `json:"allowedPaths"`
	DeniedPaths      []string `json:"deniedPaths"`
	CreatedBy        string   `json:"createdBy"`
	GitBranch        string   `json:"gitBranch"`
	GitHeadCommit    string   `json:"gitHeadCommit"`
	GitDirty         bool     `json:"gitDirty"`
	CreatedAt        string   `json:"createdAt"`
	UpdatedAt        string   `json:"updatedAt"`
}

type TaskExecutionsResp struct {
	Items []ExecutionItem `json:"items"`
}

type TaskItem struct {
	Id               string `json:"id"`
	Title            string `json:"title"`
	RepoPath         string `json:"repoPath"`
	Mode             string `json:"mode"`
	Status           string `json:"status"`
	ApprovalRequired bool   `json:"approvalRequired"`
	CreatedBy        string `json:"createdBy"`
	GitBranch        string `json:"gitBranch"`
	GitHeadCommit    string `json:"gitHeadCommit"`
	GitDirty         bool   `json:"gitDirty"`
	CreatedAt        string `json:"createdAt"`
	UpdatedAt        string `json:"updatedAt"`
}

type TaskListResp struct {
	Items []TaskItem `json:"items"`
}

type TaskLogsResp struct {
	Items []LogItem `json:"items"`
}
