// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ApproveTaskReq struct {
	Id         string `path:"id"`
	ReviewerId string `json:"reviewerId"`
	Reason     string `json:"reason,optional"`
}

type ApproveTaskResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type CancelTaskReq struct {
	Id        string `path:"id"`
	ActorId   string `json:"actorId"`
	ActorRole string `json:"actorRole,options=creator|reviewer|admin"`
	Reason    string `json:"reason,optional"`
}

type CancelTaskResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type CreateTaskReq struct {
	Title            string   `json:"title"`
	RepoPath         string   `json:"repoPath"`
	Prompt           string   `json:"prompt"`
	CreatorId        string   `json:"creatorId"`
	ReviewerId       string   `json:"reviewerId,optional"`
	OperatorId       string   `json:"operatorId,optional"`
	Mode             string   `json:"mode,options=analyze|patch"`
	ApprovalRequired bool     `json:"approvalRequired,optional"`
	MaxSteps         int64    `json:"maxSteps,default=10"`
	AllowedPaths     []string `json:"allowedPaths,optional"`
	DeniedPaths      []string `json:"deniedPaths,optional"`
}

type CreateTaskResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type ExecutionItem struct {
	Id            string `json:"id"`
	TaskId        string `json:"taskId"`
	OperatorId    string `json:"operatorId"`
	Status        string `json:"status"`
	StartedAt     string `json:"startedAt"`
	FinishedAt    string `json:"finishedAt"`
	ResultSummary string `json:"resultSummary"`
	ErrorMessage  string `json:"errorMessage"`
}

type FailTaskReq struct {
	Id            string `path:"id"`
	OperatorId    string `json:"operatorId"`
	ResultSummary string `json:"resultSummary,optional"`
	ErrorMessage  string `json:"errorMessage"`
}

type FailTaskResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type GetTaskExecutionsReq struct {
	Id string `path:"id"`
}

type GetTaskLogsReq struct {
	Id string `path:"id"`
}

type GetTaskReq struct {
	Id string `path:"id"`
}

type GetTaskStatusHistoriesReq struct {
	Id string `path:"id"`
}

type LogItem struct {
	Step       int64  `json:"step"`
	Level      string `json:"level"`
	Message    string `json:"message"`
	ToolName   string `json:"toolName"`
	OccurredAt string `json:"occurredAt"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"accessToken"`
	ExpiresIn   int64  `json:"expiresIn"`
}

type StartTaskReq struct {
	Id         string `path:"id"`
	OperatorId string `json:"operatorId"`
}

type StartTaskResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type StatusHistoryItem struct {
	Id         string `json:"id"`
	FromStatus string `json:"fromStatus"`
	ToStatus   string `json:"toStatus"`
	Action     string `json:"action"`
	ActorId    string `json:"actorId"`
	ActorRole  string `json:"actorRole"`
	Reason     string `json:"reason"`
	CreatedAt  string `json:"createdAt"`
}

type SucceedTaskReq struct {
	Id            string `path:"id"`
	OperatorId    string `json:"operatorId"`
	ResultSummary string `json:"resultSummary,optional"`
}

type SucceedTaskResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type TaskDetailResp struct {
	Id               string   `json:"id"`
	Title            string   `json:"title"`
	RepoPath         string   `json:"repoPath"`
	Prompt           string   `json:"prompt"`
	Mode             string   `json:"mode"`
	Status           string   `json:"status"`
	ApprovalRequired bool     `json:"approvalRequired"`
	MaxSteps         int64    `json:"maxSteps"`
	AllowedPaths     []string `json:"allowedPaths"`
	DeniedPaths      []string `json:"deniedPaths"`
	CreatorId        string   `json:"creatorId"`
	ReviewerId       string   `json:"reviewerId"`
	OperatorId       string   `json:"operatorId"`
	ApprovedBy       string   `json:"approvedBy"`
	ApprovedAt       string   `json:"approvedAt"`
	CancelledBy      string   `json:"cancelledBy"`
	CancelledAt      string   `json:"cancelledAt"`
	GitBranch        string   `json:"gitBranch"`
	GitHeadCommit    string   `json:"gitHeadCommit"`
	GitDirty         bool     `json:"gitDirty"`
	CreatedAt        string   `json:"createdAt"`
	UpdatedAt        string   `json:"updatedAt"`
}

type TaskExecutionsResp struct {
	Items []ExecutionItem `json:"items"`
}

type TaskItem struct {
	Id               string `json:"id"`
	Title            string `json:"title"`
	RepoPath         string `json:"repoPath"`
	Mode             string `json:"mode"`
	Status           string `json:"status"`
	ApprovalRequired bool   `json:"approvalRequired"`
	CreatorId        string `json:"creatorId"`
	GitBranch        string `json:"gitBranch"`
	GitHeadCommit    string `json:"gitHeadCommit"`
	GitDirty         bool   `json:"gitDirty"`
	CreatedAt        string `json:"createdAt"`
	UpdatedAt        string `json:"updatedAt"`
}

type TaskListResp struct {
	Items []TaskItem `json:"items"`
}

type TaskLogsResp struct {
	Items []LogItem `json:"items"`
}

type TaskStatusHistoriesResp struct {
	Items []StatusHistoryItem `json:"items"`
}
