// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "agentops/internal/handler/auth"
	tasks "agentops/internal/handler/tasks"
	"agentops/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/tasks",
				Handler: tasks.CreateTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tasks",
				Handler: tasks.ListTasksHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tasks/:id",
				Handler: tasks.GetTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tasks/:id/approve",
				Handler: tasks.ApproveTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tasks/:id/cancel",
				Handler: tasks.CancelTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tasks/:id/executions",
				Handler: tasks.GetTaskExecutionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tasks/:id/logs",
				Handler: tasks.GetTaskLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tasks/:id/start",
				Handler: tasks.StartTaskHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
