package tasks

import "errors"

var (
	ErrTaskIDRequired              = errors.New("id is required")
	ErrInvalidTaskID               = errors.New("id must be a numeric task id")
	ErrTaskNotFound                = errors.New("task not found")
	ErrTitleRequired               = errors.New("title is required")
	ErrCreatorIDRequired           = errors.New("creatorId is required")
	ErrReviewerIDRequired          = errors.New("reviewerId is required")
	ErrRepoPathRequired            = errors.New("repoPath is required")
	ErrRepoNotGitRepo              = errors.New("repoPath must point to a git repository")
	ErrPromptRequired              = errors.New("prompt is required")
	ErrInvalidMode                 = errors.New("mode must be analyze or patch")
	ErrInvalidMaxSteps             = errors.New("maxSteps must be greater than 0")
	ErrErrorMessageRequired        = errors.New("errorMessage is required")
	ErrTaskNotWaitingApproval      = errors.New("task is not waiting for approval")
	ErrTaskNotPending              = errors.New("task is not pending")
	ErrOperatorIDRequired          = errors.New("operatorId is required")
	ErrCancelActorIDRequired       = errors.New("actorId is required")
	ErrInvalidCancelActorRole      = errors.New("actorRole must be creator, reviewer or admin")
	ErrCancelActorNotAllowed       = errors.New("actorId is not allowed to cancel this task")
	ErrReviewerIDMismatch          = errors.New("reviewerId does not match assigned reviewer")
	ErrOperatorIDMismatch          = errors.New("operatorId does not match assigned operator")
	ErrExecutionOperatorMismatch   = errors.New("operatorId does not match running execution operator")
	ErrTaskCannotBeCancelled       = errors.New("task cannot be cancelled from current status")
	ErrRepoHasNoCommits            = errors.New("git repository has no commits yet")
	ErrTaskNotRunning              = errors.New("task is not running")
	ErrRunningExecutionNotFound    = errors.New("running execution not found")
	ErrPermissionDenied            = errors.New("permission denied")
	ErrExecutionPolicyRequired     = errors.New("execution policy is required")
	ErrAllowedPathRequiredForPatch = errors.New("allowedPaths is required for patch execution")
	ErrInvalidPolicyPath           = errors.New("policy path must be relative and stay inside repo")
	ErrRepoNotAllowed              = errors.New("repoPath is not allowed for execution")
	ErrChangedFileDenied           = errors.New("changed file matches deniedPaths")
	ErrChangedFileNotAllowed       = errors.New("changed file is outside allowedPaths")
)
